// lib/Community/Map/map_placeholders.dart
// Pure data — no widget or build logic.
// Placeholder organisations give the map a lived-in feel at zero real data.
// Progressively emptied as real organisations onboard via Firestore.

import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'map.dart'; // MapOrganization, MapAmenity, AmenityType

// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER ORGANISATIONS
// ─────────────────────────────────────────────────────────────────────────────

const List<MapOrganization> kPlaceholderOrgs = [
  MapOrganization(
    id: 'org_001',
    name: 'Kibera Plastics Collective',
    description:
    'Collecting and processing plastic waste from Kibera into pellets and recycled products for resale.',
    location: LatLng(-1.3120, 36.7810),
    sectorId: 'sector_env',
    orgTypeId: 'ot_recycler',
    subTypeIds: ['st_plastic_recycler', 'st_mixed_recycler'],
    beneficiaryGroupIds: ['bg_youth', 'bg_women', 'bg_general'],
    facilityTypeIds: ['facility_collection_point', 'facility_drop_off'],
    subFacilityIds: ['sf_plastic_drop', 'sf_general_drop'],
    legalDesignation: 'CBO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Kibera',
    verified: true,
  ),
  MapOrganization(
    id: 'org_002',
    name: 'Sanaa ya Taka (Waste Art Co-op)',
    description:
    'Transforming plastic waste and scrap metal into sculptures, ornaments, and handmade jewellery sold globally.',
    location: LatLng(-1.3000, 36.7670),
    sectorId: 'sector_env',
    orgTypeId: 'ot_waste_art',
    subTypeIds: ['st_plastic_art', 'st_ornament_maker'],
    beneficiaryGroupIds: ['bg_women', 'bg_youth'],
    facilityTypeIds: ['facility_workshop', 'facility_gallery'],
    subFacilityIds: ['sf_art_studio', 'sf_sewing_studio'],
    legalDesignation: 'Social Enterprise',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Kawangware',
    verified: true,
  ),
  MapOrganization(
    id: 'org_003',
    name: 'Amka Girls Initiative',
    description:
    'Empowering girls through mentorship, menstrual health education, and anti-FGM advocacy in Mathare.',
    location: LatLng(-1.2597, 36.8581),
    sectorId: 'sector_social',
    orgTypeId: 'ot_girls_org',
    subTypeIds: ['st_girl_mentorship', 'st_girl_menstrual_health', 'st_girl_safety'],
    beneficiaryGroupIds: ['bg_girls', 'bg_teen_mothers'],
    facilityTypeIds: ['facility_community_center', 'facility_drop_in_center'],
    subFacilityIds: ['sf_counseling_room', 'sf_resource_center'],
    legalDesignation: 'NGO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Mathare',
    verified: true,
  ),
  MapOrganization(
    id: 'org_004',
    name: 'Tupendane PWD Center',
    description:
    'Rehabilitation, assistive devices, and vocational training for persons with physical and intellectual disabilities.',
    location: LatLng(-1.3158, 36.8269),
    sectorId: 'sector_social',
    orgTypeId: 'ot_pwd_org',
    subTypeIds: ['st_physical_disability', 'st_intellectual_disability', 'st_assistive_tech'],
    beneficiaryGroupIds: ['bg_pwd', 'bg_children', 'bg_youth'],
    facilityTypeIds: ['facility_rehabilitation_center', 'facility_training_center'],
    subFacilityIds: ['sf_tailoring_unit', 'sf_ict_lab'],
    legalDesignation: 'NPO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'South B',
    verified: false,
  ),
  MapOrganization(
    id: 'org_005',
    name: 'Mama na Mtoto Health Clinic',
    description:
    'Maternal and child health clinic providing ANC, immunization, and HIV testing services to Kibera residents.',
    location: LatLng(-1.3125, 36.7825),
    sectorId: 'sector_health',
    orgTypeId: 'ot_clinic',
    subTypeIds: ['st_maternal_clinic', 'st_hiv_center'],
    beneficiaryGroupIds: ['bg_women', 'bg_children', 'bg_girls'],
    facilityTypeIds: ['facility_clinic'],
    subFacilityIds: ['sf_antenatal', 'sf_hiv_testing', 'sf_pharmacy'],
    legalDesignation: 'NGO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Olympic Estate, Kibera',
    verified: true,
    phone: '+254700000001',
  ),
  MapOrganization(
    id: 'org_006',
    name: 'Tabasamu Women Enterprise',
    description:
    'Women savings cooperative supporting 200+ members with microcredit, business training, and market linkages.',
    location: LatLng(-1.2833, 36.8167),
    sectorId: 'sector_social',
    orgTypeId: 'ot_women_org',
    subTypeIds: ['st_women_enterprise', 'st_women_empowerment'],
    beneficiaryGroupIds: ['bg_women'],
    facilityTypeIds: ['facility_office', 'facility_training_center'],
    subFacilityIds: ['sf_arts_studio'],
    legalDesignation: 'SACCO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Ngara',
    verified: true,
  ),
  MapOrganization(
    id: 'org_007',
    name: 'Nairobi River Guardians',
    description:
    'Monthly cleanup drives along the Nairobi River, with waste quantification reports and school education programs.',
    location: LatLng(-1.3175, 36.7875),
    sectorId: 'sector_env',
    orgTypeId: 'ot_cleanup_org',
    subTypeIds: ['st_river_cleanup', 'st_community_cleanup'],
    beneficiaryGroupIds: ['bg_youth', 'bg_general'],
    facilityTypeIds: ['facility_collection_point'],
    subFacilityIds: ['sf_general_drop'],
    legalDesignation: 'CBO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Westlands — Nairobi River',
    verified: true,
  ),
  MapOrganization(
    id: 'org_008',
    name: "Upendo Children's Home",
    description:
    'Caring for 150 orphaned and abandoned children with housing, full-time schooling, and psychosocial support.',
    location: LatLng(-1.2400, 36.8700),
    sectorId: 'sector_social',
    orgTypeId: 'ot_children_org',
    subTypeIds: ['st_orphan_care', 'st_child_education'],
    beneficiaryGroupIds: ['bg_children', 'bg_orphans'],
    facilityTypeIds: ['facility_shelter', 'facility_school'],
    subFacilityIds: ['sf_emergency_shelter', 'sf_primary', 'sf_library'],
    legalDesignation: 'Trust',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Roysambu',
    verified: true,
  ),
  MapOrganization(
    id: 'org_009',
    name: 'Kibera WASH Point',
    description:
    'Clean water access, communal latrines, and hygiene promotion across 5 villages in Kibera.',
    location: LatLng(-1.3140, 36.7840),
    sectorId: 'sector_health',
    orgTypeId: 'ot_wash',
    subTypeIds: ['st_water_access', 'st_sanitation'],
    beneficiaryGroupIds: ['bg_general', 'bg_children'],
    facilityTypeIds: ['facility_water_point'],
    subFacilityIds: ['sf_public_tap', 'sf_latrine_block', 'sf_handwashing'],
    legalDesignation: 'CBO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Kibera, Olympic Estate',
    verified: true,
  ),
  MapOrganization(
    id: 'org_010',
    name: 'FutureMakers Youth Hub',
    description:
    'ICT training, graphic design, and entrepreneurship programs for youth aged 18–30 in Ngara.',
    location: LatLng(-1.2667, 36.8333),
    sectorId: 'sector_social',
    orgTypeId: 'ot_youth_org',
    subTypeIds: ['st_youth_skills', 'st_youth_enterprise', 'st_youth_arts'],
    beneficiaryGroupIds: ['bg_youth', 'bg_boys', 'bg_girls'],
    facilityTypeIds: ['facility_youth_center', 'facility_training_center'],
    subFacilityIds: ['sf_ict_lab', 'sf_entrepreneurship_hub', 'sf_recording_studio'],
    legalDesignation: 'NPO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Ngara',
    verified: false,
  ),
  MapOrganization(
    id: 'org_011',
    name: 'Taka Treasure Upcyclers',
    description:
    'Handcrafted upcycled furniture and home goods from reclaimed wood, tyres, and metal scrap.',
    location: LatLng(-1.2921, 36.7856),
    sectorId: 'sector_env',
    orgTypeId: 'ot_waste_art',
    subTypeIds: ['st_furniture_maker', 'st_mixed_craft'],
    beneficiaryGroupIds: ['bg_youth', 'bg_men'],
    facilityTypeIds: ['facility_workshop'],
    subFacilityIds: ['sf_fabrication_shop'],
    legalDesignation: 'Social Enterprise',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Kilimani',
    verified: false,
  ),
  MapOrganization(
    id: 'org_012',
    name: 'Haki Legal Aid Centre',
    description:
    'Free legal aid for survivors of GBV, land disputes, and child rights violations across Nairobi.',
    location: LatLng(-1.2864, 36.8172),
    sectorId: 'sector_legal',
    orgTypeId: 'ot_legal_aid',
    subTypeIds: ['st_gbv_legal', 'st_land_rights', 'st_child_legal'],
    beneficiaryGroupIds: ['bg_women', 'bg_children', 'bg_pwd'],
    facilityTypeIds: ['facility_legal_aid_office'],
    subFacilityIds: [],
    legalDesignation: 'NGO',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'CBD',
    verified: true,
    phone: '+254722000002',
    website: 'https://hakilegal.example.org',
  ),
  // ── New community & sports orgs (sector_community) ──────────────────────
  MapOrganization(
    id: 'org_013',
    name: 'Kibera United FC',
    description:
    'Kibera Super League side with 180 registered players. Weekly training at Olympic Primary grounds. Runs youth camps for under-16s.',
    location: LatLng(-1.3135, 36.7820),
    sectorId: 'sector_community',
    orgTypeId: 'ot_football_club',
    subTypeIds: ['st_football_11'],
    beneficiaryGroupIds: ['bg_youth', 'bg_boys'],
    facilityTypeIds: ['facility_sports_ground'],
    subFacilityIds: [],
    legalDesignation: 'Sports Club',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Kibera',
    verified: false,
  ),
  MapOrganization(
    id: 'org_014',
    name: 'Mathare Cultural Arts Collective',
    description:
    'Traditional dance, spoken word, and community drama productions rooted in Mathare oral history.',
    location: LatLng(-1.2580, 36.8600),
    sectorId: 'sector_community',
    orgTypeId: 'ot_drama_choir',
    subTypeIds: ['st_drama', 'st_traditional_dance'],
    beneficiaryGroupIds: ['bg_youth', 'bg_women', 'bg_general'],
    facilityTypeIds: ['facility_community_center'],
    subFacilityIds: ['sf_art_studio'],
    legalDesignation: 'Community Group (informal)',
    country: 'Kenya',
    city: 'Nairobi',
    area: 'Mathare',
    verified: false,
  ),
];

// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER AMENITIES
// ─────────────────────────────────────────────────────────────────────────────

final List<MapAmenity> kPlaceholderAmenities = [
  MapAmenity(
    id: 'amenity_001',
    name: 'Laini Saba Water Point',
    amenityType: AmenityType.waterPoint,
    location: const LatLng(-1.3130, 36.7835),
    description: 'Community standpipe — operational Mon–Sat 6am–7pm.',
    operatingHours: 'Mon–Sat 6:00am–7:00pm',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_002',
    name: 'Olympic Estate Plastic Drop-Off',
    amenityType: AmenityType.recyclingDropOff,
    location: const LatLng(-1.3118, 36.7848),
    description: 'Accepts PET, HDPE, carrier bags. Operated by Kibera Plastics Collective.',
    acceptedMaterials: ['PET', 'HDPE', 'Carrier bags', 'Soft plastic'],
    operatingHours: 'Daily 8:00am–5:00pm',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_003',
    name: 'Gatwekera Dumpsite',
    amenityType: AmenityType.dumpsite,
    location: const LatLng(-1.3155, 36.7798),
    description: 'Active illegal dumpsite — reported by 4 community members. Cleanup bounty available.',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_004',
    name: 'Canopy Kibera Hub',
    amenityType: AmenityType.canopyHub,
    location: const LatLng(-1.3108, 36.7862),
    description: 'Canopy solar processing hub. Accepts plastic for weighing and payment via M-Pesa.',
    acceptedMaterials: ['PET', 'HDPE', 'LDPE', 'PP', 'Carrier bags'],
    operatingHours: 'Mon–Fri 7:30am–6:00pm, Sat 8:00am–2:00pm',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_005',
    name: 'Nairobi River Cleanup — Sat 22 Feb',
    amenityType: AmenityType.cleanupEvent,
    location: const LatLng(-1.3170, 36.7880),
    description: 'Monthly cleanup along the Nairobi River bank. Organised by Nairobi River Guardians.',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_006',
    name: 'Karura Community Tree Planting',
    amenityType: AmenityType.treeSite,
    location: const LatLng(-1.2290, 36.8245),
    description: '200 indigenous trees planted — 90-day survival verification ongoing.',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_007',
    name: 'Mathare North WASH Station',
    amenityType: AmenityType.waterPoint,
    location: const LatLng(-1.2560, 36.8595),
    description: 'Handwashing station and communal tap — installed by WASH Kenya 2024.',
    operatingHours: 'Always open',
    isActive: true,
  ),
  MapAmenity(
    id: 'amenity_008',
    name: 'Kangemi Dumpsite',
    amenityType: AmenityType.dumpsite,
    location: const LatLng(-1.2700, 36.7640),
    description: 'Large unmanaged dumpsite near drainage channel. High priority for bounty listing.',
    isActive: true,
  ),
];